### ISSUE TITLE
キャラクターや建物に画像を設定する？

### ISSUE THREAD

**Issue by mon2929** [stomachachers/picmin#17]
主人公は今の赤丸のままでいきますか？

**Comment by Dozi0116** [comment]
@obtknt が書いてくれた主人公画像にするか検討中。
こっちで試してみて、細かくてわかりにくそうだったりしたら、今のまま赤丸で行く。

**Comment by Dozi0116** [comment]
主人公の色と、地面の色が似通ってたから、赤丸のままで制作します。

**Comment by Dozi0116** [comment]
建物に関しては、画像を設定しないでいいと思う。
仮に設定するとしたら、他の部分(緑色の部分、津波部分)もなんか凝ったほうが…ってキリ無くなりそう
